### ISSUE TITLE
change doctests to use `cabal-doctest`

### ISSUE THREAD

**Issue by cdepillabout** [cdepillabout/pretty-simple#49]
Recent versions of `stack` (anything after stack-2.1), have changed so that doctests no longer work.

I believe that doctests need to be using the [`cabal-doctest`](http://hackage.haskell.org/package/cabal-doctest) package in order to work correctly when compiling with `stack`.

pretty-simple's doctests need to be switched over to use `cabal-doctest`.

This should also make CI stop failing when building with `stack`.

**Comment by chshersh** [comment]
That's highly unfortunate that simple `doctest` doesn't work. I believe that this has something to do with `.ghc.environment` files. They are crucial for `doctest` to work, but it was a long debate to stop generating these files.

Unfortunately, `cabal-doctest` is not always a drop-in replacement for plain `doctest` because usage of `cabal-doctest` requires to use `custom-setup` stanza and with this stanza, you can't have internal libraries (last time I checked).

**Comment by cdepillabout** [comment]
> with `custom-setup`, you can't have internal libraries (last time I checked).

Oh, I didn't realize this.

I guess this should be okay for now, since `pretty-simple` doesn't have any internal libraries, but I can imagine just using `cabal-doctest` isn't a good solution for everyone.
