### ISSUE TITLE
Make it easier to install the CLI tool

### ISSUE THREAD

**Issue by georgefst** [cdepillabout/pretty-simple#90]
Given that `cabal install` no longer means anything for a library (since Cabal 3.0), there's an argument for removing the `buildexe` flag entirely, so that `cabal install pretty-simple` just does the right thing.

@cdepillabout Am I missing anything?

**Comment by cdepillabout** [comment]
I agree with this.

When I originally added the CLI tool, I really thought it was something that only I would ever use, so I hid it behind a flag.  I didn't want it accidentally getting installed if people did `stack install pretty-simple` or pulled it in with Nix.

It turns out other people have found it useful, and like you say, it is easy to just not install it if you don't want it.

I'd be fine with removing the flag, or even just defaulting it to `True`.

**Comment by georgefst** [comment]
Defaulting to true seems nicer actually - backwards-compatible with old instructions, and it's an even more trivial change.
